#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Trisha | Registration: 24BAC10012
# Course: Open Source Software | OSS NGMC Capstone
# Description: Interactively asks the user three questions,
#              then generates a personalised open source
#              philosophy statement saved to a .txt file.
# ============================================================

# --- Alias demonstration (as per course requirement) ---
# In a real session, aliases work like shortcuts for commands
# alias today='date +"%d %B %Y"'   # would let you type 'today' instead of full date command
# alias greet='echo "Hello, open source world!"'

# --- Output file name includes username for personalisation ---
OUTPUT="manifesto_$(whoami).txt"

# --- Current date for the manifesto timestamp ---
DATE=$(date '+%d %B %Y')

# --- Header ---
echo "=================================================================="
echo "  OPEN SOURCE MANIFESTO GENERATOR"
echo "  Student: Trisha | Reg: 24BAC10012"
echo "=================================================================="
echo ""
echo "  Answer three questions to generate your personal open source"
echo "  philosophy statement. Be honest — this is your manifesto."
echo ""
echo "------------------------------------------------------------------"

# --- Interactive user input using 'read' ---
# -p flag displays the prompt inline before reading input

# Question 1: A tool they use every day
read -p "  1. Name one open-source tool you use every day: " TOOL

# Validate that user didn't leave it blank
while [ -z "$TOOL" ]; do
    echo "  Please enter a tool name."
    read -p "  1. Name one open-source tool you use every day: " TOOL
done

echo ""

# Question 2: What freedom means to them in one word
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM

# Validate input
while [ -z "$FREEDOM" ]; do
    echo "  Please enter one word."
    read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
done

echo ""

# Question 3: Something they would build and share freely
read -p "  3. Name one thing you would build and share freely: " BUILD

# Validate input
while [ -z "$BUILD" ]; do
    echo "  Please enter something you would build."
    read -p "  3. Name one thing you would build and share freely: " BUILD
done

echo ""
echo "------------------------------------------------------------------"
echo "  Generating your manifesto..."
echo "------------------------------------------------------------------"
echo ""

# --- Compose the manifesto using string concatenation ---
# Write to output file using > (creates/overwrites) and >> (appends)

# Clear the file first (or create it) using >
echo "" > "$OUTPUT"

# Write the manifesto header
echo "==================================================================" >> "$OUTPUT"
echo "  MY OPEN SOURCE MANIFESTO" >> "$OUTPUT"
echo "  Generated by: $(whoami)" >> "$OUTPUT"
echo "  Date: $DATE" >> "$OUTPUT"
echo "  Course: Open Source Software | VITyarthi" >> "$OUTPUT"
echo "==================================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Write the personalised philosophy paragraph using the user's answers
# This demonstrates string concatenation — variables embedded in strings
echo "  Every day, I rely on $TOOL — a tool that exists because someone," >> "$OUTPUT"
echo "  somewhere, decided that their work was worth sharing with the" >> "$OUTPUT"
echo "  world at no cost and with no conditions other than that others" >> "$OUTPUT"
echo "  must do the same. That decision was not just practical. It was" >> "$OUTPUT"
echo "  a statement about values." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  To me, freedom means $FREEDOM. In the context of software, that" >> "$OUTPUT"
echo "  means the right to look inside the tools I depend on, to change" >> "$OUTPUT"
echo "  them when they do not work the way I need, and to pass them on" >> "$OUTPUT"
echo "  to others better than I found them. Richard Stallman could not" >> "$OUTPUT"
echo "  fix a printer because the source code was locked. I believe no" >> "$OUTPUT"
echo "  one who uses a tool should ever be in that position again." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  If I could build one thing and share it freely, it would be" >> "$OUTPUT"
echo "  $BUILD. I would release it under the GPL, because I want the" >> "$OUTPUT"
echo "  freedom I give to flow forward and never be taken back. The" >> "$OUTPUT"
echo "  giants whose shoulders I stand on — Torvalds, Stallman, and" >> "$OUTPUT"
echo "  thousands of unnamed contributors — built in the open. I intend" >> "$OUTPUT"
echo "  to do the same." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Open source is not just a licensing model. It is a belief that" >> "$OUTPUT"
echo "  knowledge shared is knowledge multiplied, and that the tools" >> "$OUTPUT"
echo "  which shape the world should be owned by the world." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "==================================================================" >> "$OUTPUT"
echo "  Signed: $(whoami) | $DATE" >> "$OUTPUT"
echo "==================================================================" >> "$OUTPUT"

# --- Display confirmation and show the generated file ---
echo "  Manifesto saved to: $OUTPUT"
echo ""
echo "=================================================================="
echo "  YOUR MANIFESTO"
echo "=================================================================="
echo ""

# Display the contents of the generated manifesto
cat "$OUTPUT"
